version: '3'

services:
  games_proxy:
    image: postgres:14
    container_name: games_proxy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sakila_games
    volumes:
      - ./init/proxy_setup.sql:/docker-entrypoint-initdb.d/proxy_setup.sql
    ports:
      - "5433:5432"
    networks:
      - games_network

  games_shard1:
    image: postgres:14
    container_name: games_shard1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sakila_games
    volumes:
      - ./init/games_shard1.sql:/docker-entrypoint-initdb.d/games_shard1.sql
    networks:
      - games_network

  games_shard2:
    image: postgres:14
    container_name: games_shard2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sakila_games
    volumes:
      - ./init/games_shard2.sql:/docker-entrypoint-initdb.d/games_shard2.sql
    networks:
      - games_network

networks:
  games_network:
    driver: bridge

