CREATE TABLE "users" (
	"id" INTEGER NOT NULL UNIQUE,
	"full_name" VARCHAR(255),
	"nickname" VARCHAR(255),
	"email" VARCHAR(255),
	"pswd_hash" TEXT,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"birthday" DATE,
	"phone_number" CHAR(1),
	"location" VARCHAR(255),
	PRIMARY KEY("id")
);

CREATE TABLE "tags" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" TEXT,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE TABLE "games" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(60),
	"description" TEXT,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"author_id" INTEGER,
	PRIMARY KEY("id")
);

CREATE TABLE "friendships" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER,
	"friend_id" INTEGER,
	"status" VARCHAR(255),
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE TABLE "jams" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" CHAR(1),
	"author_id" INTEGER,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"start_date" TIMESTAMP,
	"deadline" TIMESTAMP,
	"end_date" TIMESTAMP,
	"description" TEXT,
	PRIMARY KEY("id")
);

CREATE TABLE "jams_tags" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"jam_id" INTEGER,
	"tag_id" INTEGER,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE TABLE "notifications" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"recipient_id" INTEGER,
	"actor_id" INTEGER,
	"action" VARCHAR(255),
	"read" BOOLEAN,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE TABLE "reviews" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER,
	"user_mark" DECIMAL,
	"criterion" VARCHAR(255),
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"game_id" INTEGER,
	"jam_id" INTEGER,
	PRIMARY KEY("id")
);

CREATE TABLE "sessions" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER,
	"session_id" VARCHAR(255),
	"ip_address" VARCHAR(255),
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"browser" VARCHAR(255),
	PRIMARY KEY("id")
);

CREATE TABLE "game_tags" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"game_id" INTEGER,
	"tag_id" INTEGER,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

ALTER TABLE "games"
ADD FOREIGN KEY("id") REFERENCES "game_tags"("game_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "tags"
ADD FOREIGN KEY("id") REFERENCES "game_tags"("tag_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "jams_tags"
ADD FOREIGN KEY("jam_id") REFERENCES "jams"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "jams"
ADD FOREIGN KEY("author_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "games"("author_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "friendships"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "friendships"
ADD FOREIGN KEY("friend_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "notifications"("recipient_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "reviews"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "sessions"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "reviews"
ADD FOREIGN KEY("jam_id") REFERENCES "jams"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "tags"
ADD FOREIGN KEY("id") REFERENCES "jams_tags"("tag_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "reviews"
ADD FOREIGN KEY("game_id") REFERENCES "games"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;