global:
  scrape_interval: 10s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alert_rules.yml"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets:
        - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'node-exp'
    static_configs:
      - targets: ['node-exp:9100']

  - job_name: 'postgres-exporter-games'
    static_configs:
      - targets: ['postgres-exporter-games:9187']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'games_proxy'
      - source_labels: []
        target_label: domain
        replacement: 'games'

  - job_name: 'postgres-exporter-jams'
    static_configs:
      - targets: ['postgres-exporter-jams:9187']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'jams_proxy'
      - source_labels: []
        target_label: domain
        replacement: 'jams'

  - job_name: 'postgres-exporter-reviews'
    static_configs:
      - targets: ['postgres-exporter-reviews:9187']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'reviews_proxy'
      - source_labels: []
        target_label: domain
        replacement: 'reviews'

  - job_name: 'postgres-exporter-users'
    static_configs:
      - targets: ['postgres-exporter-users:9187']
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'users_proxy'
      - source_labels: []
        target_label: domain
        replacement: 'users'
