-- Настройка прокси для домена "Теги"
-- Создание расширения для работы с внешними данными
CREATE EXTENSION IF NOT EXISTS postgres_fdw;

-- Создание серверов для доступа к другим доменам
CREATE SERVER games_proxy FOREIGN DATA WRAPPER postgres_fdw
    OPTIONS (host 'games_proxy', port '5432', dbname 'sakila_games');

CREATE SERVER jams_proxy FOREIGN DATA WRAPPER postgres_fdw
    OPTIONS (host 'jams_proxy', port '5432', dbname 'sakila_jams');

-- Создание пользовательских маппингов
CREATE USER MAPPING FOR postgres SERVER games_proxy
    OPTIONS (user 'postgres', password 'postgres');

CREATE USER MAPPING FOR postgres SERVER jams_proxy
    OPTIONS (user 'postgres', password 'postgres');

-- Создание таблицы tags
CREATE TABLE tags (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    name TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY(id)
);

-- Создание внешних таблиц для доступа к связанным таблицам в других доменах
CREATE FOREIGN TABLE game_tags (
    id INTEGER,
    game_id INTEGER,
    tag_id INTEGER,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
) SERVER games_proxy OPTIONS (schema_name 'public', table_name 'game_tags');

CREATE FOREIGN TABLE jams_tags (
    id INTEGER,
    jam_id INTEGER,
    tag_id INTEGER,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
) SERVER jams_proxy OPTIONS (schema_name 'public', table_name 'tags');

-- Вставка тестовых данных для тегов
INSERT INTO tags (id, name, created_at, updated_at) VALUES 
(1, 'Action', NOW(), NOW()),
(2, 'Adventure', NOW(), NOW()),
(3, 'RPG', NOW(), NOW()),
(4, 'Strategy', NOW(), NOW()),
(5, 'Simulation', NOW(), NOW());

-- Функция для обновления тегов в других доменах
CREATE OR REPLACE FUNCTION update_tags_in_domains()
RETURNS TRIGGER AS $$
BEGIN
    -- Здесь должен быть код для обновления тегов в других доменах
    -- Это может быть реализовано через вызов хранимых процедур в других доменах
    -- или через прямое обновление данных в других доменах
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Триггер для обновления тегов в других доменах
CREATE TRIGGER trg_update_tags
AFTER INSERT OR UPDATE ON tags
FOR EACH ROW
EXECUTE FUNCTION update_tags_in_domains();

