{
 "title": "Jammer service",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Games connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{state=\"active\", datname=\"games\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jams connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"jams\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reviews connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{state=\"active\", datname=\"reviews\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reviews connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{state=\"active\", datname=\"reviews\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Games", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Games for today",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "games_today_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average games rating",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_rating_avg", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Games Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "games_total_count", "legendFormat": "__auto" }
   ]
  },
  { "title": "Jams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total Jams",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_jams_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total active jams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 26 },
   "targets": [
    { "expr": "total_active_jams_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Upcoming Jmas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upcoming_jams_count", "legendFormat": "__auto" }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Total users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_users_count", "legendFormat": "__auto" }
   ]
  }
 ]
}