version: '3'

services:
  users_proxy:
    image: postgres:14
    container_name: users_proxy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sakila_users
    volumes:
      - ./init/proxy_setup.sql:/docker-entrypoint-initdb.d/proxy_setup.sql
    ports:
      - "5432:5432"
    networks:
      - users_network

  users_shard1:
    image: postgres:14
    container_name: users_shard1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sakila_users
    volumes:
      - ./init/users_shard1.sql:/docker-entrypoint-initdb.d/users_shard1.sql
    networks:
      - users_network

  users_shard2:
    image: postgres:14
    container_name: users_shard2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sakila_users
    volumes:
      - ./init/users_shard2.sql:/docker-entrypoint-initdb.d/users_shard2.sql
    networks:
      - users_network

networks:
  users_network:
    driver: bridge

