version: '3'

services:
  tags_proxy:
    image: postgres:14
    container_name: tags_proxy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sakila_tags
    volumes:
      - ./init/proxy_setup.sql:/docker-entrypoint-initdb.d/proxy_setup.sql
    ports:
      - "5436:5432"
    networks:
      - tags_network

networks:
  tags_network:
    driver: bridge

